import os
import git
from typing import Dict, Any

class GitManager:
    """
    Manages Git operations via strict MCP constraints.
    Ensures safe rollback states are created before refactoring begins,
    and provides deterministic rollback mechanisms if semantic drift is detected.
    """

    def __init__(self, repo_path: str = "."):
        self.repo_path = repo_path
        try:
            self.repo = git.Repo(self.repo_path)
        except git.InvalidGitRepositoryError:
            # Eğer kod bir Git reposu içinde çalışmıyorsa (ki bizimki çalışıyor), hata vermemesi için:
            print("Uyarı: Geçerli bir Git reposu bulunamadı, init ediliyor...")
            self.repo = git.Repo.init(self.repo_path)

    def save_state(self, commit_message: str = "AutoRefactorOps: Pre-refactor safety state") -> Dict[str, Any]:
        """
        Creates a Git commit to save the exact state of the codebase before the LLM touches it.
        """
        try:
            self.repo.git.add(A=True)
            # Eğer kaydedilecek yeni bir değişiklik yoksa boşuna commit atma
            if not self.repo.is_dirty(untracked_files=True):
                return {
                    "success": True, 
                    "message": "Çalışma alanı zaten temiz, güvenlik commit'ine gerek yok.", 
                    "commit_hash": None
                }
            
            commit = self.repo.index.commit(commit_message)
            return {
                "success": True, 
                "message": "Güvenlik durumu kaydedildi.", 
                "commit_hash": commit.hexsha
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def rollback(self) -> Dict[str, Any]:
        """
        Rolls back the repository to the last commit via hard reset.
        Destroys any hallucinated or broken code generated by the Refactoring Agent.
        """
        try:
            # Kodları son commit'e geri çevir (git reset --hard HEAD)
            self.repo.git.reset('--hard', 'HEAD')
            # LLM'in uydurarak yarattığı yeni takip edilmeyen dosyalar varsa onları da sil (git clean -fd)
            self.repo.git.clean('-fd')
            return {"success": True, "message": "Başarıyla son güvenli duruma geri dönüldü (Rollback successful)."}
        except Exception as e:
            return {"success": False, "error": str(e)}

if __name__ == "__main__":
    # Test Senaryosu
    print("--- Git Manager Güvenlik Testi ---")
    gm = GitManager()
    
    # 1. Mevcut durumu kaydetmeyi dene
    save_result = gm.save_state("Test: Refactor öncesi durum")
    print(f"Durum Kaydı: {save_result.get('message')}")
    
    # 2. Rollback yapmayı dene
    rollback_result = gm.rollback()
    print(f"Geri Sarma (Rollback): {rollback_result.get('message')}")