import os
import git
from typing import Dict, Any

class GitManager:
    """
    Manages Git operations via strict MCP constraints.
    Ensures safe rollback states are created before refactoring begins,
    and provides deterministic rollback mechanisms if semantic drift is detected.
    """

    def __init__(self, repo_path: str = "."):
        self.repo_path = repo_path
        try:
            self.repo = git.Repo(self.repo_path)
        except git.InvalidGitRepositoryError:
            print("Warning: No valid Git repository found, initializing...")
            self.repo = git.Repo.init(self.repo_path)

    def save_state(self, commit_message: str = "AutoRefactorOps: Pre-refactor safety state") -> Dict[str, Any]:
        """
        Creates a Git commit to save the exact state of the codebase before the LLM touches it.
        """
        try:
            self.repo.git.add(A=True)
            if not self.repo.is_dirty(untracked_files=True):
                return {
                    "success": True, 
                    "message": "Working directory is clean, no safety commit needed.", 
                    "commit_hash": None
                }
            
            commit = self.repo.index.commit(commit_message)
            return {
                "success": True, 
                "message": "Safety state saved successfully.", 
                "commit_hash": commit.hexsha
            }
        except Exception as e:
            return {"success": False, "error": str(e)}

    def rollback(self) -> Dict[str, Any]:
        """
        Rolls back the repository to the last commit via hard reset.
        Destroys any hallucinated or broken code generated by the Refactoring Agent.
        """
        try:
            self.repo.git.reset('--hard', 'HEAD')
            self.repo.git.clean('-fd')
            return {"success": True, "message": "Successfully rolled back to the last safe state."}
        except Exception as e:
            return {"success": False, "error": str(e)}

if __name__ == "__main__":
    print("--- Git Manager Safety Test ---")
    gm = GitManager()
    
    save_result = gm.save_state("Test: Pre-refactor state")
    print(f"State Save: {save_result.get('message')}")
    
    rollback_result = gm.rollback()
    print(f"Rollback: {rollback_result.get('message')}")